# Site settings
title: BadiCoin
description: The coin for real Badigals
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://badico.in' # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: BadiCoin (BADI)
user_description: The BadiCoin changes your style
user_title: The coin for real Badigals
email: pinas@badico.in
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules']
